#!/bin/bash

set -e
set -x

# Front
pushd src/main/front
yarn install
yarn build
popd

# Back
mvn clean
mvn package -P prod

# linux/amd64
docker build --platform linux/amd64 --build-arg JAR_FILE=target/*.jar -t agaspard/home-admin-amd64 .

# linux/arm32
docker build --platform linux/arm --build-arg JAR_FILE=target/*.jar -t agaspard/home-admin-arm32 .
