
spring:
  application:
    name: authentication-service
  flyway:
    locations: classpath:db/migration
server:
  servlet:
    context-path: /api

app:
  mail:
    mail-address: <noreply@local.fr>
  security:
    cors:
      allowed-origin-patterns: '*'
      allowed-methods: '*'
      allowed-headers: '*'
      exposed-headers: 'Authorization,Link,X-Total-Count'
      allow-credentials: true
      max-age: 1800

