server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/home_admin
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  mail:
    url: http://localhost:8080
  security:
    jwt:
      secret: 2FYATHOHmedvL6z57EGuYeVb3Z3lrusDesFuD3YFWK5v4UrhvlHLZKIZlmT16gvWPKNy287XPiFz7okIx3MOPOapKyCtPlTXYY53lQwqQLKX4MVoxNdtH7PL1VYz12
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
  action:
    runnable-dir: /Users/alexandre/home-admin
    execution-timeout: PT60S
#logging:
#  level:
#logging:
#  file:
#    name: app.log
#    path: /Users/alexandre/repos/home-admin
