
spring:
  application:
    name: authentication-service
  flyway:
    locations: classpath:db/migration
  web:
    resources:
      static-locations: classpath:/static/

app:
  mail:
    mail-address: <noreply@local.fr>
  security:
    cors:
      allowed-origin-patterns: 'http://localhost:3000'
      allowed-methods: '*'
      allowed-headers: '*'
      exposed-headers: 'Authorization,Link,X-Total-Count'
      allow-credentials: true
      max-age: 1800

